---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-mongodb-init"
  annotations:
    helm.sh/hook: "post-install,post-upgrade"
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: "before-hook-creation"
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mongodb-init
          image: mongo:7.0
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "{{ .Values.env.MONGO_REPORTS_USERNAME }}"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "{{ .Values.env.MONGO_REPORTS_PASSWORD }}"
            - name: MONGO_REPORTS_DATABASE
              value: "{{ .Values.env.MONGO_REPORTS_DATABASE }}"
            - name: MONGO_REPORTS_USERNAME
              value: "{{ .Values.env.MONGO_REPORTS_USERNAME }}"
            - name: MONGO_REPORTS_PASSWORD
              value: "{{ .Values.env.MONGO_REPORTS_PASSWORD }}"
          command:
            - /bin/sh
            - -c
            - |
              mongosh --host mongodb --username $MONGO_INITDB_ROOT_USERNAME --password $MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin --eval "
                db = db.getSiblingDB('$MONGO_REPORTS_DATABASE');
                db.createUser({
                  user: '$MONGO_REPORTS_USERNAME',
                  pwd: '$MONGO_REPORTS_PASSWORD',
                  roles: [{ role: 'readWrite', db: '$MONGO_REPORTS_DATABASE' }]
                });
              "
  backoffLimit: 4